import { Router } from 'express';
import type { AppContext } from './context.js';
import { agentsRoutes } from './agents.js';
import { rolesRoutes } from './roles.js';
import { configRoutes } from './config.js';
import { coordinationRoutes } from './coordination.js';
import { leadRoutes } from './lead.js';
import { decisionsRoutes } from './decisions.js';
import { searchRoutes } from './search.js';
import { browseRoutes } from './browse.js';
import { projectsRoutes } from './projects.js';
import { sessionsRoutes } from './sessions.js';
import { dbRoutes } from './db.js';
import { servicesRoutes } from './services.js';
import { diffRoutes } from './diff.js';
import { replayRoutes } from './replay.js';
import { commsRoutes } from './comms.js';
import { summaryRoutes } from './summary.js';
import { sharedRoutes } from './shared.js';
import { analyticsRoutes } from './analytics.js';
import { notificationRoutes } from './notifications.js';
import { nlRoutes } from './nl.js';
import { conflictRoutes } from './conflicts.js';
import { dataRoutes } from './data.js';
import { knowledgeRoutes } from './knowledge.js';
import { teamsRoutes } from './teams.js';
import { settingsRoutes } from './settings.js';
import { integrationRoutes } from './integrations.js';
import { tasksRoutes } from './tasks.js';

export function mountAllRoutes(router: Router, ctx: AppContext): void {
  router.use(agentsRoutes(ctx));
  router.use(rolesRoutes(ctx));
  router.use(configRoutes(ctx));
  router.use(coordinationRoutes(ctx));
  router.use(leadRoutes(ctx));
  router.use(decisionsRoutes(ctx));
  router.use(searchRoutes(ctx));
  router.use(browseRoutes(ctx));
  router.use(projectsRoutes(ctx));
  router.use(sessionsRoutes(ctx));
  router.use(dbRoutes(ctx));
  router.use(servicesRoutes(ctx));
  router.use(diffRoutes(ctx));
  router.use(replayRoutes(ctx));
  router.use(commsRoutes(ctx));
  router.use(summaryRoutes(ctx));
  router.use(sharedRoutes(ctx));
  router.use(analyticsRoutes(ctx));

  router.use(notificationRoutes(ctx));
  router.use(nlRoutes(ctx));
  router.use(conflictRoutes(ctx));
  router.use(dataRoutes(ctx));
  router.use(knowledgeRoutes(ctx));
  router.use(teamsRoutes(ctx));
  router.use(settingsRoutes(ctx));
  router.use(integrationRoutes(ctx));
  router.use(tasksRoutes(ctx));
}
