<template>
  <footer class="doc-footer-note">
    Documentation generated by AI
  </footer>
</template>

<style scoped>
.doc-footer-note {
  margin-top: 2rem;
  padding: 1.5rem 0;
  border-top: 1px solid var(--vp-c-divider);
  text-align: center;
  font-size: 14px;
  color: var(--vp-c-text-3);
}
</style>
