/**
 * Cross-CLI Role File Writers.
 *
 * Each CLI has a different format for agent definition files.
 * RoleFileWriter translates Flightdeck role definitions into
 * CLI-specific files so each CLI can discover and use custom roles.
 *
 * See docs/research/custom-agents-cross-cli.md for format details.
 */
import { mkdir, writeFile, readdir, unlink, readFile } from 'fs/promises';
import { join, resolve, sep } from 'path';

// ── Types ───────────────────────────────────────────────────────────

export interface RoleDefinition {
  /** Role identifier, e.g. 'developer', 'architect' */
  role: string;
  /** Short description of the role */
  description: string;
  /** Full system prompt / instructions for the agent */
  instructions: string;
  /** Optional list of tool names the agent can use */
  tools?: string[];
}

export interface RoleFileWriter {
  /** Write CLI-specific agent files for the given roles. Returns paths of written files. */
  writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]>;
  /** Remove previously generated Flightdeck agent files. */
  cleanRoleFiles(targetDir: string): Promise<void>;
  /** Return a human-readable format identifier. */
  getFormat(): string;
}

// ── Constants ───────────────────────────────────────────────────────

/** Marker comment embedded in generated markdown files for identification. */
export const FLIGHTDECK_MARKER = '<!-- Generated by Flightdeck. Do not edit manually. -->';

const FLIGHTDECK_JSON_KEY = '_generatedByFlightdeck';

/** Only lowercase alphanumeric characters and hyphens are allowed in role names. */
const VALID_ROLE_NAME = /^[a-z0-9][a-z0-9-]*$/;

// ── Copilot: .github/agents/<role>.agent.md ─────────────────────────

export class CopilotRoleFileWriter implements RoleFileWriter {
  getFormat(): string {
    return 'copilot-agent-md';
  }

  async writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]> {
    const dir = join(targetDir, '.github', 'agents');
    await mkdir(dir, { recursive: true });

    const writtenFiles: string[] = [];
    for (const role of roles) {
      validateRoleName(role.role);
      const filename = `flightdeck-${role.role}.agent.md`;
      const filePath = join(dir, filename);
      assertPathWithinDir(filePath, dir);
      const toolsList = (role.tools?.length ? role.tools : ['read', 'edit', 'search', 'shell'])
        .map((t) => `  - ${t}`)
        .join('\n');

      const content = [
        FLIGHTDECK_MARKER,
        '---',
        `name: flightdeck-${role.role}`,
        `description: "${escapeYamlString(role.description)}"`,
        'tools:',
        toolsList,
        '---',
        '',
        `# ${capitalize(role.role)} — Flightdeck Agent`,
        '',
        role.instructions,
        '',
      ].join('\n');

      await writeFile(filePath, content, 'utf-8');
      writtenFiles.push(filePath);
    }
    return writtenFiles;
  }

  async cleanRoleFiles(targetDir: string): Promise<void> {
    const dir = join(targetDir, '.github', 'agents');
    await removeMatchingFlightdeckFiles(dir, 'flightdeck-', '.agent.md');
  }
}

// ── Claude: .claude/agents/<role>.md ────────────────────────────────

export class ClaudeRoleFileWriter implements RoleFileWriter {
  getFormat(): string {
    return 'claude-agent-md';
  }

  async writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]> {
    const dir = join(targetDir, '.claude', 'agents');
    await mkdir(dir, { recursive: true });

    const writtenFiles: string[] = [];
    for (const role of roles) {
      validateRoleName(role.role);
      const filename = `flightdeck-${role.role}.md`;
      const filePath = join(dir, filename);
      assertPathWithinDir(filePath, dir);

      const content = [
        FLIGHTDECK_MARKER,
        '---',
        `name: flightdeck-${role.role}`,
        `description: "${escapeYamlString(role.description)}"`,
        '---',
        '',
        `# ${capitalize(role.role)}`,
        '',
        role.instructions,
        '',
      ].join('\n');

      await writeFile(filePath, content, 'utf-8');
      writtenFiles.push(filePath);
    }
    return writtenFiles;
  }

  async cleanRoleFiles(targetDir: string): Promise<void> {
    const dir = join(targetDir, '.claude', 'agents');
    await removeMatchingFlightdeckFiles(dir, 'flightdeck-', '.md');
  }
}

// ── Gemini: .gemini/agents/<role>.md ────────────────────────────────

export class GeminiRoleFileWriter implements RoleFileWriter {
  getFormat(): string {
    return 'gemini-agent-md';
  }

  async writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]> {
    const dir = join(targetDir, '.gemini', 'agents');
    await mkdir(dir, { recursive: true });

    const writtenFiles: string[] = [];
    for (const role of roles) {
      validateRoleName(role.role);
      const filename = `flightdeck-${role.role}.md`;
      const filePath = join(dir, filename);
      assertPathWithinDir(filePath, dir);
      const content = [
        FLIGHTDECK_MARKER,
        '',
        `# ${capitalize(role.role)}`,
        '',
        `> ${role.description}`,
        '',
        role.instructions,
        '',
      ].join('\n');

      await writeFile(filePath, content, 'utf-8');
      writtenFiles.push(filePath);
    }
    return writtenFiles;
  }

  async cleanRoleFiles(targetDir: string): Promise<void> {
    const dir = join(targetDir, '.gemini', 'agents');
    await removeMatchingFlightdeckFiles(dir, 'flightdeck-', '.md');
  }
}

// ── Cursor: .cursor/rules/<role>.mdc ────────────────────────────────

export class CursorRoleFileWriter implements RoleFileWriter {
  getFormat(): string {
    return 'cursor-mdc';
  }

  async writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]> {
    const dir = join(targetDir, '.cursor', 'rules');
    await mkdir(dir, { recursive: true });

    const writtenFiles: string[] = [];
    for (const role of roles) {
      validateRoleName(role.role);
      const filename = `flightdeck-${role.role}.mdc`;
      const filePath = join(dir, filename);
      assertPathWithinDir(filePath, dir);

      const content = [
        FLIGHTDECK_MARKER,
        '---',
        `description: "${escapeYamlString(role.description)}"`,
        'alwaysApply: true',
        '---',
        '',
        `# ${capitalize(role.role)}`,
        '',
        role.instructions,
        '',
      ].join('\n');

      await writeFile(filePath, content, 'utf-8');
      writtenFiles.push(filePath);
    }
    return writtenFiles;
  }

  async cleanRoleFiles(targetDir: string): Promise<void> {
    const dir = join(targetDir, '.cursor', 'rules');
    await removeMatchingFlightdeckFiles(dir, 'flightdeck-', '.mdc');
  }
}

// ── Codex: AGENTS.md (single file, all agents) ─────────────────────

export class CodexRoleFileWriter implements RoleFileWriter {
  getFormat(): string {
    return 'codex-agents-md';
  }

  async writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]> {
    for (const role of roles) {
      validateRoleName(role.role);
    }
    await mkdir(targetDir, { recursive: true });
    const filePath = join(targetDir, 'AGENTS.md');

    const sections = roles.map(
      (role) =>
        [`## ${capitalize(role.role)}`, '', `> ${role.description}`, '', role.instructions].join(
          '\n',
        ),
    );

    const content = [
      FLIGHTDECK_MARKER,
      '',
      '# Flightdeck Agents',
      '',
      sections.join('\n\n---\n\n'),
      '',
    ].join('\n');

    await writeFile(filePath, content, 'utf-8');
    return [filePath];
  }

  async cleanRoleFiles(targetDir: string): Promise<void> {
    const filePath = join(targetDir, 'AGENTS.md');
    await removeIfFlightdeckGenerated(filePath);
  }
}

// ── OpenCode: opencode.json ─────────────────────────────────────────

export class OpenCodeRoleFileWriter implements RoleFileWriter {
  getFormat(): string {
    return 'opencode-json';
  }

  async writeRoleFiles(roles: RoleDefinition[], targetDir: string): Promise<string[]> {
    for (const role of roles) {
      validateRoleName(role.role);
    }
    await mkdir(targetDir, { recursive: true });
    const filePath = join(targetDir, 'opencode.json');

    // Preserve existing config if present
    let config: Record<string, unknown> = {};
    try {
      const existing = await readFile(filePath, 'utf-8');
      config = JSON.parse(existing) as Record<string, unknown>;
    } catch {
      // No existing file or invalid JSON — start fresh
    }

    // Build the flightdeck agents
    const agents: Record<string, unknown> = {};
    for (const role of roles) {
      const entry: Record<string, unknown> = {
        description: role.description,
        prompt: role.instructions,
      };
      if (role.tools?.length) {
        entry.tools = Object.fromEntries(role.tools.map((t) => [t, 'allow']));
      }
      agents[`flightdeck-${role.role}`] = entry;
    }

    // Merge with existing agents (flightdeck entries overwrite, others preserved)
    const existingAgents = (config.agents as Record<string, unknown>) ?? {};
    config.agents = { ...existingAgents, ...agents };
    config[FLIGHTDECK_JSON_KEY] = true;

    await writeFile(filePath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
    return [filePath];
  }

  async cleanRoleFiles(targetDir: string): Promise<void> {
    const filePath = join(targetDir, 'opencode.json');
    try {
      const existing = await readFile(filePath, 'utf-8');
      const config = JSON.parse(existing) as Record<string, unknown>;

      if (!config[FLIGHTDECK_JSON_KEY]) return;

      // Remove flightdeck agent entries
      const agents = config.agents as Record<string, unknown> | undefined;
      if (agents) {
        for (const key of Object.keys(agents)) {
          if (key.startsWith('flightdeck-')) {
            delete agents[key];
          }
        }
        if (Object.keys(agents).length === 0) {
          delete config.agents;
        }
      }
      delete config[FLIGHTDECK_JSON_KEY];

      if (Object.keys(config).length === 0) {
        await unlink(filePath);
      } else {
        await writeFile(filePath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
      }
    } catch {
      // File doesn't exist or invalid JSON — nothing to clean
    }
  }
}

// ── Factory ─────────────────────────────────────────────────────────

const WRITER_FACTORIES: Record<string, () => RoleFileWriter> = {
  copilot: () => new CopilotRoleFileWriter(),
  claude: () => new ClaudeRoleFileWriter(),
  gemini: () => new GeminiRoleFileWriter(),
  cursor: () => new CursorRoleFileWriter(),
  codex: () => new CodexRoleFileWriter(),
  opencode: () => new OpenCodeRoleFileWriter(),
};

/**
 * Create a RoleFileWriter for the given CLI provider.
 * @throws Error if the provider ID is not recognized.
 */
export function createRoleFileWriter(providerId: string): RoleFileWriter {
  const factory = WRITER_FACTORIES[providerId];
  if (!factory) {
    throw new Error(
      `No RoleFileWriter for provider "${providerId}". ` +
        `Valid providers: ${Object.keys(WRITER_FACTORIES).join(', ')}`,
    );
  }
  return factory();
}

/** List all supported provider IDs for role file writing. */
export function listRoleFileWriterProviders(): string[] {
  return Object.keys(WRITER_FACTORIES);
}

// ── Helpers ─────────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function escapeYamlString(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Validate a role name is safe for use in file paths.
 * Prevents path traversal via crafted role names like '../../.git/hooks/post-commit'.
 * @throws Error if the role name contains invalid characters.
 */
function validateRoleName(role: string): void {
  if (!VALID_ROLE_NAME.test(role)) {
    throw new Error(
      `Invalid role name "${role}". Role names must match /^[a-z0-9][a-z0-9-]*$/ ` +
        `(lowercase alphanumeric and hyphens, starting with alphanumeric).`,
    );
  }
}

/**
 * Verify a resolved file path stays within the expected base directory.
 * Defense-in-depth against path traversal even if validateRoleName is bypassed.
 * @throws Error if the resolved path escapes the base directory.
 */
function assertPathWithinDir(filePath: string, baseDir: string): void {
  const resolvedPath = resolve(filePath);
  const resolvedBase = resolve(baseDir) + sep;
  if (!resolvedPath.startsWith(resolvedBase)) {
    throw new Error(`Path traversal detected: "${filePath}" escapes base directory "${baseDir}".`);
  }
}

/** Remove files in a directory that match a prefix+suffix and contain the Flightdeck marker. */
async function removeMatchingFlightdeckFiles(
  dir: string,
  prefix: string,
  suffix: string,
): Promise<void> {
  try {
    const files = await readdir(dir);
    for (const file of files) {
      if (file.startsWith(prefix) && file.endsWith(suffix)) {
        const filePath = join(dir, file);
        try {
          const content = await readFile(filePath, 'utf-8');
          if (content.startsWith(FLIGHTDECK_MARKER)) {
            await unlink(filePath);
          }
        } catch {
          // Skip files we can't read
        }
      }
    }
  } catch {
    // Directory doesn't exist — nothing to clean
  }
}

/** Remove a file only if it starts with the Flightdeck marker. */
async function removeIfFlightdeckGenerated(filePath: string): Promise<void> {
  try {
    const content = await readFile(filePath, 'utf-8');
    if (content.startsWith(FLIGHTDECK_MARKER)) {
      await unlink(filePath);
    }
  } catch {
    // File doesn't exist — nothing to clean
  }
}
