import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Flightdeck',
  description: 'Multi-Agent Orchestration Platform',
  base: '/',
  head: [['link', { rel: 'icon', href: '/favicon.ico' }]],
  themeConfig: {
    logo: '/logo.svg',
    nav: [
      { text: 'Guide', link: '/guide/' },
      { text: 'Features', link: '/guide/features' },
      { text: 'Reference', link: '/reference/api' },
      { text: 'Blog', link: '/blog/introducing-flightdeck' },
      { text: 'GitHub', link: 'https://github.com/justinchuby/flightdeck' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Getting Started',
          items: [
            { text: 'Introduction', link: '/guide/' },
            { text: 'Quick Start', link: '/guide/quickstart' },
            { text: 'Features Overview', link: '/guide/features' },
            { text: 'Smart Onboarding', link: '/guide/onboarding' },
          ],
        },
        {
          text: 'Core Concepts',
          items: [
            { text: 'Architecture', link: '/guide/architecture' },
            { text: 'Roles & Agents', link: '/guide/roles' },
            { text: 'Agent Commands', link: '/guide/commands' },
            { text: 'Command Syntax', link: '/guide/command-syntax' },
            { text: 'Command Design', link: '/guide/command-design' },
            { text: 'Coordination', link: '/guide/coordination' },
            { text: 'Multiproject Isolation', link: '/guide/multiproject-isolation' },
            { text: 'Crew Status & Heartbeat', link: '/guide/crew-status' },
            { text: 'Auto-DAG', link: '/guide/auto-dag' },
            { text: 'TIDE Protocol', link: '/guide/tide-protocol' },
          ],
        },
        {
          text: 'Communication',
          items: [
            { text: 'Agent Communication', link: '/guide/agent-communication' },
            { text: 'Chat Groups', link: '/guide/chat-groups' },
            { text: 'Chat UI Architecture', link: '/guide/chat-architecture' },
          ],
        },
        {
          text: 'Dashboard',
          items: [
            { text: 'Lead Dashboard', link: '/guide/dashboard-lead' },
            { text: 'Agents View', link: '/guide/dashboard-agents' },
            { text: 'Settings', link: '/guide/dashboard-settings' },
            { text: 'UI Design', link: '/guide/ui-design' },
          ],
        },
        {
          text: 'Features',
          items: [
            { text: 'Command Palette', link: '/guide/command-palette' },
            { text: 'Intent Rules', link: '/guide/intent-rules' },
            { text: 'Data Management', link: '/guide/data-management' },
            { text: 'Mobile PWA', link: '/guide/mobile' },
          ],
        },
        {
          text: 'Timeline',
          items: [
            { text: 'Timeline UI', link: '/guide/timeline' },
            { text: 'Accessibility', link: '/guide/timeline-accessibility' },
            { text: 'Architecture', link: '/guide/timeline-architecture' },
          ],
        },
        {
          text: 'Development',
          items: [
            { text: 'Developer Guide', link: '/guide/developer-guide' },
            { text: 'Usage Tips & Use Cases', link: '/guide/usage-tips' },
          ],
        },
      ],
      '/blog/': [
        {
          text: 'Blog',
          items: [
            { text: 'Introducing Flightdeck', link: '/blog/introducing-flightdeck' },
          ],
        },
      ],
      '/reference/': [
        {
          text: 'API Reference (Internal)',
          items: [
            { text: 'REST API', link: '/reference/api' },
            { text: 'WebSocket Events', link: '/reference/websocket' },
            { text: 'Timeline Components', link: '/reference/timeline-api' },
            { text: 'Database Schema', link: '/reference/database' },
          ],
        },
        {
          text: 'Feature APIs (Internal)',
          items: [
            { text: 'NL Commands', link: '/reference/nl-api' },
          ],
        },
        {
          text: 'Architecture (Internal)',
          items: [
            { text: 'Configuration', link: '/reference/configuration' },
            { text: 'Architecture Decisions', link: '/reference/architecture-decisions' },
            { text: 'Design Decisions', link: '/reference/design-decisions' },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/justinchuby/flightdeck' },
    ],
    search: { provider: 'local' },
    footer: {
      message: 'Documentation generated by AI',
    },
  },
})
